# Generated by Django 2.2.7 on 2019-11-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_board_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('menu', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=5)),
                ('bread', models.CharField(max_length=15)),
                ('add', models.CharField(max_length=15)),
            ],
        ),
    ]
